### ISSUE TITLE
"chariot" search

### ISSUE THREAD

**Issue by joeafletch** [nathan-rice/erdman#1]
@nathan-rice I think I've discovered why the "chariot" result that Joe V. isolated today wasn't showing up: the instance of "chariot" on page 643 (Reynolds Marginalia) occurs between angle brackets, which get <add> tags in the xml. I haven't talked to Mike about this yet, but I'm guessing that the search isn't picking up text between these tags--I've tried in a couple more instances and got the same non-result. I'll talk to Mike about this, but if you have any suggestions for how to get around this, let us know.

**Comment by nathan-rice** [comment]
Fixed.
